distribution:
  entryPoint: src/installer.js
  keywords:
  - claude
  - parallel
  - development
  - git
  - worktree
  - linear
  - automation
  - cli
  - npx
  - workflow
  scripts:
  - executable: true
    name: cache-linear-issue.py
    path: scripts/python/cache-linear-issue.py
  - executable: true
    name: decompose-parallel.py
    path: scripts/python/decompose-parallel.py
  - executable: true
    name: spawn-agents.py
    path: scripts/python/spawn-agents.py
  type: global-npx-package
package: '@aojdevstudio/cdev'
publishStatus:
  globalInstallTested: true
  npmVerified: true
  published: true
  publishedAt: '2025-07-28T16:17:46.758991'
publishedAt: '2025-07-28T16:17:22.602962'
validation:
  buildClean: true
  filesValidated: 5
  scriptsValidated: 3
version: 0.0.17
